spring:
  datasource:
    url: jdbc:postgresql://classdb.chdrd1esgtl4.us-east-2.rds.amazonaws.com/postgres
    
server:
  port: 5000
  
---
  # Configuration for local development environment
spring:
  profiles: local
 
  datasource:
    username: hibernate_role
    password: top-secret
    hikari:
      # Database connection pool size
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        temp:
          use_jdbc_metadata_default: false
---

# Configuration for cloud development environment
spring:
  profiles: development
  